
###
GET http://127.0.0.1:3000/inventory HTTP/1.1

###
GET http://127.0.0.1:3000/api/inventory/0 HTTP/1.1

###
POST http://127.0.0.1:3000/inventory HTTP/1.1
content-type: application/json

{
	"name": "HTL",
	"serial": "001",
	"quantity": 2,
	"dateEntry": "2012-10-20",
	"description": "this is my description"
}

### 
PUT http://127.0.0.1:3000/inventory/60e5fca3844f77406d3aa812 HTTP/1.1
content-type: application/json 

{
	"name": "HTL",
	"serial": "001",
	"quantity": 2,
	"date": "2-10-20",
	"description": "this is my updated description"
}



###
DELETE http://127.0.0.1:3000/inventory/60e5fca3844f77406d3aa812 HTTP/1.1




###
DELETE http://127.0.0.1:3000/inventory HTTP/1.1




